### ISSUE TITLE
Zgłoszenia z różnych postaci

### ISSUE THREAD

**Issue by PheonXen** [yavi/xoriat-pub#14]
Obecnie aktywna postać zawsze wypowiada się w zgłoszeniu, nawet jak nie dotyczy tej postaci. Przykład:
Klepanie postaci X, aktywuję postać Y, komentuję w postaci X jako postać Y.

**Comment by yavi** [comment]
Z założenia to która postać się wypowiada w zgłoszeniu jest nieistotne (zgłoszenia są gracza, której postaci ono dotyczy jest i tak widoczne w temacie).
