### ISSUE TITLE
Błędne nazewnictwo aktywności postaci.

### ISSUE THREAD

**Issue by PheonXen** [yavi/xoriat-pub#15]
Gdy wchodzimy w postaci możemy sobie "Aktywować" postać, ale potem, gdy nie mamy akcepta gra nas informuje, że nie możemy zrobić większości rzeczy, bo nie mamy aktywnej postaci.

**Comment by yavi** [comment]
Poprawione - nie można już aktywować niezaakceptowanej postaci.
