### ISSUE TITLE
Kreator Postaci

### ISSUE THREAD

**Issue by Rawij** [yavi/xoriat-pub#19]
Kreator Postaci zapamiętuje poprzednie wybory dotyczące aspektów, utrapienia, koncepcji, etc, także podczas tworzenia nowej postaci - wpisane są wybory dotyczące starej.

**Comment by Eonka** [comment]
bo on miał być chyba zatrzymywać na wypadek zamknięcia karty/straty prądu itd.?

**Comment by Rawij** [comment]
Tak, ale nawet jak robię nową postać, to mam wpisane wszystko co wpisałem poprzedniej postaci, już zrobionej

**Comment by arachneae** [comment]
To jest coś za coś. Z jednej strony masz to zapisane, jak robisz nową postac, z drugiej nigdy nie stracisz wypełnionego formularza/odpisu itd.

**Comment by yavi** [comment]
Zrobione (znaczy teraz nie zapisuje niczego ;P )
