### ISSUE TITLE
Zapis pw w zakładaniu sesji

### ISSUE THREAD

**Issue by Eonka** [yavi/xoriat-pub#22]
>Wysłałam wiadomość prywatną
>Tworzę sesję publiczną
>Zapisany jest tytuł, kto jest odbiorcą i treść z wysłanej już wiadomości

Wiem, że to związane z zapisywaniem rzeczy, ale wtedy może jakiś przycisk do szybkiego "czyszczenia" tych pól?

**Comment by Eonka** [comment]
Dotyczy to też zgłoszeń, tekst się do innych rzeczy zapisuje

**Comment by yavi** [comment]
Fixed.
