### ISSUE TITLE
Karczmy.

### ISSUE THREAD

**Issue by PheonXen** [yavi/xoriat-pub#23]
Karczmy źle znoszą długie ciągi znaków. Potrafi wyjść za ekran nawet. Niby nic, ale może ktoś kiedyś będzie potrzebować bardzo długi ciąg znaków bez spacji dać.

**Comment by PheonXen** [comment]
Nie ma edycji postów w karczmie, a przydałoby się. Chociażby dopóki nie ma nowej wiadomości. 
Czy avki w karczmie serio są potrzebne? I wszystkie te ozdobniki? Sprawia to, że miejsca na tekstu zostaje niewiele.

**Comment by Eonka** [comment]
Avki akurat nie przeszkadzają zbytnio (przynajmniej mi), ale może właśnie opcja w opcjach, by móc wybrać sobie czy się je widzi?
Przy "ozdobnikach" odzielających chyba starczy tylko zmniejszyć odległość od tekstu i będzie lepiej
