### ISSUE TITLE
Dodawanie ludzi do sesji. 

### ISSUE THREAD

**Issue by PheonXen** [yavi/xoriat-pub#24]
1. Mogę (chyba) dodawać ludzi do nie moich sesji. 
2. Jak dodałem jedną osobę, to zaraz potem miałem: 
https://i.gyazo.com/d9e659f8e0b2db18166a995610a021c5.png

**Comment by PheonXen** [comment]
Jednak nie mogę dodać, ale wykrzacza na 403 jak próbuję.

**Comment by yavi** [comment]
Fixed.
