### ISSUE TITLE
Prywaty.

### ISSUE THREAD

**Issue by PheonXen** [yavi/xoriat-pub#25]
https://i.gyazo.com/996c13dade9fb4a6d8a945e8bb0a8d05.png

Mogę sobie jeździć z rozwijaną listą po ekranie. :D

**Comment by PheonXen** [comment]
Zapamiętuje ludzi dodanych do poprzedniej sesji/wiadomości prywatnej i AUTOMATYCZNIE ich dodaje do następnej. Słabo jak niechcący się wyśle nudle nie tam gdzie trza.

**Comment by Eonka** [comment]
o tym drugim już pisałam wcześniej ;P

**Comment by PheonXen** [comment]
Jest przycisk na dół, nie ma przycisk na górę.

**Comment by yavi** [comment]
Fixed.
