### ISSUE TITLE
Straszne ułożenie okna pisania odpisu i głupoty sesji

### ISSUE THREAD

**Issue by Eonka** [yavi/xoriat-pub#27]
1. Jest on na górze, a najnowsze odpisy na dole - co wymaga duuużo jeżdżenia, jest niewygodne i czasochłonne.
2. Co prowadzi do drugiej sprawy, że sesja nie ma "stron" i się pisze nieskończoność. Na razie dojechaliśmy do 51 postów
3. Pole edytora jest za duże, w sensie za długie. Ogólnie to raczej rzadziej się pisze takie molochy, niż paroakapitowe odpisy

**Comment by yavi** [comment]
Poprawione (poza stronnicowaniem).
