### ISSUE TITLE
Niemożność obniżania cech poniżej "niewielka:

### ISSUE THREAD

**Issue by Rawij** [yavi/xoriat-pub#3]
Nie da się odjąć cechy, chyba że zmieni się rasę z dodatnim modyfikatorem do tejże cechy, odejmie, a następnie zmieni na taką bez modyfikatora, co obniża daną cechę o wartość modyfikatora.

**Comment by yavi** [comment]
Cech nie da się obniżać poniżej `niewielka`, natomiast błędem jest że majstrowanie przy rasach pozwala to ominąć.
