### ISSUE TITLE
Kreator Postaci

### ISSUE THREAD

**Issue by Shagarot** [yavi/xoriat-pub#33]
W trakcie tworzenia nowej postaci, kliknąłem na KP swojej obecnej postaci. Przy ponownej próbie wejścia w opcje tworzenia nowej postaci wyświetla mi pustą stronę. Odświeżanie ctr +F5 nic nie daje, tak samo wylogowanie i ponowne zalogowanie.

**Comment by arachneae** [comment]
Not a bug. Postać była robiona podczas prac nad silnikiem.
