### ISSUE TITLE
Sesje prywatne - blokada

### ISSUE THREAD

**Issue by Kasseris** [yavi/xoriat-pub#38]
Jak usiłuję założyć nową to wywala mi:
Ooops!!! 500
Looks like something went wrong!
We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.

(Nie, odświeżanie nie pomaga XD)

**Comment by yavi** [comment]
Naprawione w yavi/xoriat@ca8ebb16e8492f784bb3bb9fee5ae017dea824a7
