### ISSUE TITLE
Literówki

### ISSUE THREAD

**Issue by 3ldad** [yavi/xoriat-pub#5]
Przy wybieraniu pochodzenia, opis przynależności do Domu Smoczego Znamienia jest wybrakowany: 
 "uża część osób nie zwraca uwagi na to skąd wywodzi się ich ród, woląc utożsamiać się z międzynarodowym Domem Znamienia."

**Comment by 3ldad** [comment]
Opis Równin Talenty:
"Równiny talenty zamieszkują wyłącznie"
Tutaj mam problem, że w opisie Talenta jest z małej litery, a w nazwie jest z dużej.

**Comment by Eonka** [comment]
Opis odmieńców w kreatorze:
"Potomkowie sobowtórniaków mogący dowolnie zmieniać swój wygląd Odmieńcy są postrzegani przez innych z nieufnością i podejrzliwością, choć na ogół są **_o_** osoby pasywne i nieszkodliwe."

Opis magii Znamion w kreatorze, dwie kropki na końcu
"Część osób spokrewniona z rodami składającymi się na poszczególne Domy Smoczega Znamienia są ich Nosicielami. Znamiona te dają im zdolności czaropodobne, które z czasem mogą się rozwijać.."

Edit: Okrągły przycisk, przez który wchodzi się na listę swoich postaci jest podpisany "Postaci", nie miało być "Postacie"?

**Comment by Eonka** [comment]
Kreator, elfy: "Bonusy: cha++ any++ '

**Comment by yavi** [comment]
Wszystkie poprawione w yavi/xoriat@77ba7379285b9b3df97aded49821d02e771b0df1
