### ISSUE TITLE
Mało widoczne różnice w przyciskach między "wcisnięty"/"nie wciśnięty"

### ISSUE THREAD

**Issue by arachneae** [yavi/xoriat-pub#6]
![image](https://user-images.githubusercontent.com/36934817/38162188-34442a52-34dd-11e8-947b-d18e998714ec.png)
"Przycisk konta i profilu ma "czarne paski" u góry i z lewej, a pozostałe dwa przyciski z prawej i dołu.Wygląda to niejednorodnie"

Mało widoczne różnice w przyciskach między "wcisnięty"/"nie wciśnięty"

**Comment by Eonka** [comment]
Dodam drugą sprawę - przyciski sesji i pw też się wciskają po najechaniu, prawda? Bo każdy przesuwa się w inną stronę
Może zostawić wtedy same podświetlenie wzorków?
