### ISSUE TITLE
Opis słowny cech.

### ISSUE THREAD

**Issue by arachneae** [yavi/xoriat-pub#8]
Opis słowny cech jest niejasny. Umiarkowany, niewielki i przeciętny - często te słowa są traktowane jako synonimy, zamienniki. Gdyby nie wartości punktowe to nie wiedziałbym które jest co

**Comment by yavi** [comment]
Trzeba chyba gdzieś dorzucić tabelę z kolejnością (nie tylko na wiki - bezpośrednio w tooltipie  czy przy tworzeniu postaci).

**Comment by yavi** [comment]
Naprawione w yavi/xoriat@73ec7d63c02372d88fc80f39ddf89cdada51afb2
Dodane tooltipy przy cechach i umiejętnościach z listą poziomów.
